package com.example.dimensionspad

// ---------------------------------------------------------------------------
// Complete figure + token catalogue mirrored from Dimensions.cpp
// (s_listMinis + s_listTokens — IDs 0-83 and 1000-1265)
// ---------------------------------------------------------------------------
object FigureCatalogue {

    data class Figure(val id: Int, val name: String)

    val minifigs: List<Figure> = listOf(
        Figure(0,   "Blank Tag"),
        Figure(1,   "Batman"),
        Figure(2,   "Gandalf"),
        Figure(3,   "Wyldstyle"),
        Figure(4,   "Aquaman"),
        Figure(5,   "Bad Cop"),
        Figure(6,   "Bane"),
        Figure(7,   "Bart Simpson"),
        Figure(8,   "Benny"),
        Figure(9,   "Chell"),
        Figure(10,  "Cole"),
        Figure(11,  "Cragger"),
        Figure(12,  "Cyborg"),
        Figure(13,  "Cyberman"),
        Figure(14,  "Doc Brown"),
        Figure(15,  "The Doctor"),
        Figure(16,  "Emmet"),
        Figure(17,  "Eris"),
        Figure(18,  "Gimli"),
        Figure(19,  "Gollum"),
        Figure(20,  "Harley Quinn"),
        Figure(21,  "Homer Simpson"),
        Figure(22,  "Jay"),
        Figure(23,  "Joker"),
        Figure(24,  "Kai"),
        Figure(25,  "ACU Trooper"),
        Figure(26,  "Gamer Kid"),
        Figure(27,  "Krusty the Clown"),
        Figure(28,  "Laval"),
        Figure(29,  "Legolas"),
        Figure(30,  "Lloyd"),
        Figure(31,  "Marty McFly"),
        Figure(32,  "Nya"),
        Figure(33,  "Owen Grady"),
        Figure(34,  "Peter Venkman"),
        Figure(35,  "Slimer"),
        Figure(36,  "Scooby-Doo"),
        Figure(37,  "Sensei Wu"),
        Figure(38,  "Shaggy"),
        Figure(39,  "Stay Puft"),
        Figure(40,  "Superman"),
        Figure(41,  "Unikitty"),
        Figure(42,  "Wicked Witch of the West"),
        Figure(43,  "Wonder Woman"),
        Figure(44,  "Zane"),
        Figure(45,  "Green Arrow"),
        Figure(46,  "Supergirl"),
        Figure(47,  "Abby Yates"),
        Figure(48,  "Finn the Human"),
        Figure(49,  "Ethan Hunt"),
        Figure(50,  "Lumpy Space Princess"),
        Figure(51,  "Jake the Dog"),
        Figure(52,  "Harry Potter"),
        Figure(53,  "Lord Voldemort"),
        Figure(54,  "Michael Knight"),
        Figure(55,  "B.A. Baracus"),
        Figure(56,  "Newt Scamander"),
        Figure(57,  "Sonic the Hedgehog"),
        Figure(59,  "Gizmo"),
        Figure(60,  "Stripe"),
        Figure(61,  "E.T."),
        Figure(62,  "Tina Goldstein"),
        Figure(63,  "Marceline the Vampire Queen"),
        Figure(64,  "Batgirl"),
        Figure(65,  "Robin"),
        Figure(66,  "Sloth"),
        Figure(67,  "Hermione Granger"),
        Figure(68,  "Chase McCain"),
        Figure(69,  "Excalibur Batman"),
        Figure(70,  "Raven"),
        Figure(71,  "Beast Boy"),
        Figure(72,  "Betelgeuse"),
        Figure(74,  "Blossom"),
        Figure(75,  "Bubbles"),
        Figure(76,  "Buttercup"),
        Figure(77,  "Starfire")
    )

    val tokens: List<Figure> = listOf(
        Figure(1000, "Police Car"),
        Figure(1006, "Batmobile"),
        Figure(1009, "Benny's Spaceship"),
        Figure(1012, "DeLorean Time Machine"),
        Figure(1015, "Hoverboard"),
        Figure(1018, "Eagle Interceptor"),
        Figure(1021, "Swamp Skimmer"),
        Figure(1024, "Cyber-Guard"),
        Figure(1027, "K-9"),
        Figure(1030, "TARDIS"),
        Figure(1033, "Emmet's Excavator"),
        Figure(1036, "Winged Monkey"),
        Figure(1039, "Axe Chariot"),
        Figure(1042, "Shelob the Great"),
        Figure(1045, "Homer's Car"),
        Figure(1051, "Velociraptor"),
        Figure(1054, "Gyrosphere"),
        Figure(1057, "Clown Bike"),
        Figure(1060, "Mighty Lion Rider"),
        Figure(1063, "Arrow Launcher"),
        Figure(1066, "Mystery Machine"),
        Figure(1069, "Boulder Bomber"),
        Figure(1072, "Storm Fighter"),
        Figure(1075, "Blade Bike"),
        Figure(1078, "Samurai Mech"),
        Figure(1081, "Companion Cube"),
        Figure(1084, "Sentry Turret"),
        Figure(1087, "Scooby Snack"),
        Figure(1090, "Cloud Cuckoo Car"),
        Figure(1093, "Invisible Jet"),
        Figure(1096, "NinjaCopter"),
        Figure(1099, "Travelling Time Train"),
        Figure(1102, "Aqua Watercraft"),
        Figure(1105, "Drill Driver"),
        Figure(1108, "Quinn Mobile"),
        Figure(1111, "The Joker's Chopper"),
        Figure(1114, "Hover Pod"),
        Figure(1117, "Dalek"),
        Figure(1120, "Ecto-1"),
        Figure(1123, "Ghost Trap"),
        Figure(1132, "Lloyd's Golden Dragon"),
        Figure(1158, "Arcade Machine"),
        Figure(1161, "G-6155 Spy Hunter"),
        Figure(1164, "Slime Shooter"),
        Figure(1167, "Terror Dog"),
        Figure(1170, "Ancient Psychic Tandem War Elephant"),
        Figure(1173, "BMO"),
        Figure(1176, "Jakemobile"),
        Figure(1179, "Lumpy Car"),
        Figure(1182, "Lunatic Amp"),
        Figure(1185, "B.A.'s Van"),
        Figure(1188, "Phone Home"),
        Figure(1191, "Niffler"),
        Figure(1194, "Swooping Evil"),
        Figure(1197, "Ecto-1 (2016)"),
        Figure(1200, "Flash 'n' Finish"),
        Figure(1203, "R.C. Racer"),
        Figure(1206, "Hogwarts Express"),
        Figure(1209, "Enchanted Car"),
        Figure(1212, "IMF Scrambler"),
        Figure(1215, "IMF Sports Car"),
        Figure(1218, "Sonic Speedster"),
        Figure(1221, "The Tornado"),
        Figure(1224, "K.I.T.T."),
        Figure(1227, "Police Helicopter"),
        Figure(1230, "Bionic Steed"),
        Figure(1233, "Batwing"),
        Figure(1236, "Skeleton Organ"),
        Figure(1239, "One-Eyed Willy's Pirate Ship"),
        Figure(1242, "Buckbeak"),
        Figure(1245, "Saturn's Sandworm"),
        Figure(1248, "PPG Smartphone"),
        Figure(1251, "Ka-Pow Cannon"),
        Figure(1254, "Octi"),
        Figure(1257, "T-Car"),
        Figure(1260, "Spellbook of Azarath"),
        Figure(1263, "Titan Robot")
    )

    /** All figures sorted alphabetically for the picker. */
    val all: List<Figure> = (minifigs + tokens).sortedBy { it.name }
}
